#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 005: Run Unit Tests in Parallel

set -e

echo "========================================"
echo "Environment Setup: Parallel Test Configuration"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# PROJECT CONTEXT
# ============================================

echo ""
echo "Project: Pelican Panel"
echo "Spec: Run Unit Tests in Parallel on GitHub Actions"
echo "Workflow Type: Feature (CI/CD Enhancement)"
echo ""

# ============================================
# VERIFY DEPENDENCIES
# ============================================

echo "Checking dependencies..."

# Check PHP
if ! command -v php &> /dev/null; then
    echo -e "${RED}PHP is not installed${NC}"
    exit 1
fi

PHP_VERSION=$(php -r 'echo PHP_VERSION;')
echo -e "${GREEN}✓ PHP ${PHP_VERSION}${NC}"

# Check Composer
if ! command -v composer &> /dev/null; then
    echo -e "${RED}Composer is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Composer installed${NC}"

# Check if vendor directory exists
if [ ! -d "vendor" ]; then
    echo -e "${YELLOW}Installing PHP dependencies...${NC}"
    composer install --no-interaction --no-suggest --no-progress
else
    echo -e "${GREEN}✓ Dependencies installed${NC}"
fi

# Check Pest
if [ ! -f "vendor/bin/pest" ]; then
    echo -e "${RED}Pest is not installed${NC}"
    exit 1
fi

PEST_VERSION=$(vendor/bin/pest --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
echo -e "${GREEN}✓ Pest ${PEST_VERSION}${NC}"

# Verify Pest version supports --parallel flag (3.x+)
PEST_MAJOR=$(echo $PEST_VERSION | cut -d. -f1)
if [ "$PEST_MAJOR" -lt 3 ]; then
    echo -e "${RED}Pest version 3.x or higher is required for parallel testing${NC}"
    echo -e "${YELLOW}Current version: ${PEST_VERSION}${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Pest version supports --parallel flag${NC}"

# ============================================
# VERIFY TEST STRUCTURE
# ============================================

echo ""
echo "Verifying test structure..."

if [ ! -d "tests/Unit" ]; then
    echo -e "${RED}tests/Unit directory not found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ tests/Unit directory exists${NC}"

if [ ! -d "tests/Integration" ]; then
    echo -e "${RED}tests/Integration directory not found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ tests/Integration directory exists${NC}"

if [ ! -f "phpunit.xml" ]; then
    echo -e "${RED}phpunit.xml not found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ phpunit.xml exists${NC}"

if [ ! -f ".github/workflows/ci.yaml" ]; then
    echo -e "${RED}.github/workflows/ci.yaml not found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ CI workflow exists${NC}"

# ============================================
# READY TO START
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "This is a CI/CD configuration task - no local services need to be started."
echo ""
echo -e "${YELLOW}Available Commands:${NC}"
echo ""
echo "  ${GREEN}Run tests sequentially (current):${NC}"
echo "    vendor/bin/pest tests/Unit"
echo "    vendor/bin/pest tests/Integration"
echo ""
echo "  ${GREEN}Run tests in parallel (target):${NC}"
echo "    vendor/bin/pest tests/Unit --parallel"
echo "    vendor/bin/pest tests/Integration --parallel"
echo ""
echo "  ${GREEN}Run with explicit process count:${NC}"
echo "    vendor/bin/pest --processes=2"
echo ""
echo "  ${GREEN}Check CI workflow syntax:${NC}"
echo "    python3 -c \"import yaml; yaml.safe_load(open('.github/workflows/ci.yaml'))\""
echo ""
echo "========================================"
echo ""
