<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => '入力された情報に一致するアカウントが見つかりませんでした。',

    'login' => [
        'title' => 'Login to Continue',
        'button' => 'Log In',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'パスワードを忘れた場合',
        'label_help' => 'パスワードを再設定する手順を受け取るには、アカウントのメールアドレスを入力してください。',
        'button' => 'Send Email',
        'required' => [
            'email' => 'A valid email address must be provided to continue.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'Reset Password',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Passwords must be at least 8 characters in length.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Recovery Code',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'I Have My Device',
    ],

    'two_factor' => [
        'label' => '二段階認証のトークン',
        'label_help' => '続行するには、6桁の認証コードが必要です。お使いのデバイスで生成されたコードを入力してください。',
        'checkpoint_failed' => '二段階認証のコードが無効です。',
    ],

    'throttle' => 'ログイン試行回数が多すぎます。:seconds秒後にもう一度お試しください。',
    'password_requirements' => 'パスワードは8文字以上で、推測されにくいパスワードを使用してください。',
    '2fa_must_be_enabled' => '管理者は、このPanelの使用に二段階認証を必須にしています。',
];
