<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => 'Nema računa sa tim podatcima.',

    'login' => [
        'title' => 'Login to Continue',
        'button' => 'Log In',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'Zaboravio lozinku?',
        'label_help' => 'Napiši svoju email adresu računa kako bi dobio instrukcije da promjeniš lozinku.',
        'button' => 'Send Email',
        'required' => [
            'email' => 'A valid email address must be provided to continue.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'Reset Password',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Passwords must be at least 8 characters in length.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Recovery Code',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'I Have My Device',
    ],

    'two_factor' => [
        'label' => '2 Faktor Token',
        'label_help' => 'Ovaj račun ima 2 sloja provjere sigurnosti. Kako bi ste nastavili napišite kod koji je generiran od vašeg uređaja.',
        'checkpoint_failed' => '2 Faktor Token nije točan.',
    ],

    'throttle' => 'Previše pokušaja prijave. Pokušajte ponovno za :seconds sekundi.',
    'password_requirements' => 'Lozinka mora imati makar 8 karaktera i biti samo za ovu stranicu.',
    '2fa_must_be_enabled' => 'Administrator je odabrao da morate imate 2 Faktor kako bi ste koristli ovu stranicu.',
];
