<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => 'Не удалось найти аккаунт',

    'login' => [
        'title' => 'Войдите для Продолжения',
        'button' => 'Войти',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'Забыл пароль?',
        'label_help' => 'Введите свой адрес электронной почты для получения инструкций по сбросу пароля.',
        'button' => 'Send Email',
        'required' => [
            'email' => 'Для продолжения должен быть указан действительный адрес электронной почты.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'Reset Password',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Длина пароля должна составлять не менее 8 символов.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Резервный Код',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Продолжить',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'I Have My Device',
    ],

    'two_factor' => [
        'label' => 'Код 2FA',
        'label_help' => 'На этом аккаунте включена двухфакторная аутентификация. Пожалуйста, введите код из приложения аутентификатора.',
        'checkpoint_failed' => 'Неверный код 2FA',
    ],

    'throttle' => 'Слишком много попыток входа. Пожалуйста, попробуйте снова через :seconds секунд.',
    'password_requirements' => 'Пароль должен быть длиной не менее 8 символов.',
    '2fa_must_be_enabled' => 'Администратор потребовал, чтобы для вашей учетной записи была включена 2FA для доступа к панели.',
];
