<?php

return [
    'sign_in' => 'Logg inn',
    'go_to_login' => 'Gå til pålogging',
    'failed' => 'Ingen konto som samsvarer med disse opplysningene ble funnet.',

    'forgot_password' => [
        'label' => 'Glemt passord?',
        'label_help' => 'Enter your account email address to receive instructions on resetting your password.',
        'button' => 'Gjenopprett konto',
    ],

    'reset_password' => [
        'button' => 'Tilbakestill og logg inn',
    ],

    'two_factor' => [
        'label' => 'Tofaktorautentiserings kode',
        'label_help' => 'This account requires a second layer of authentication in order to continue. Please enter the code generated by your device to complete this login.',
        'checkpoint_failed' => 'Tofaktorautentiseringskoden var ugyldig.',
    ],

    'throttle' => 'For mange påloggingsforsøk. Prøv igjen om :seconds sekunder.',
    'password_requirements' => 'Passordet må være minst 8 tegn langt og bør være unikt for denne siden.',
    '2fa_must_be_enabled' => 'Administratoren krever at tofaktorautentisering aktiveres på din konto for å kunne bruke panelet.',
];
