<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => 'Ingen konto som samsvarer med disse opplysningene ble funnet.',

    'login' => [
        'title' => 'Login to Continue',
        'button' => 'Log In',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'Glemt passord?',
        'label_help' => 'Skriv inn din epostadresse for å motta instuksjoner for å resette passordet ditt.',
        'button' => 'Send Email',
        'required' => [
            'email' => 'A valid email address must be provided to continue.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'Reset Password',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Passwords must be at least 8 characters in length.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Recovery Code',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'I Have My Device',
    ],

    'two_factor' => [
        'label' => 'Tofaktorautentiserings kode',
        'label_help' => 'Kontoen krever en tostegsautentiserings kode for å kunne fortsette. Skriv inn koden fra din registerte enhet for å logge inn.',
        'checkpoint_failed' => 'Tofaktorautentiseringskoden var ugyldig.',
    ],

    'throttle' => 'For mange påloggingsforsøk. Prøv igjen om :seconds sekunder.',
    'password_requirements' => 'Passordet må være minst 8 tegn langt og bør være unikt for denne siden.',
    '2fa_must_be_enabled' => 'Administratoren krever at tofaktorautentisering aktiveres på din konto for å kunne bruke panelet.',
];
