<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => 'Nie znaleziono konta pasującego do tych danych.',

    'login' => [
        'title' => 'Login to Continue',
        'button' => 'Log In',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'Nie pamiętasz hasła?',
        'label_help' => 'Wprowadź swój adres e-mail, aby otrzymać instrukcje resetowania hasła.',
        'button' => 'Send Email',
        'required' => [
            'email' => 'A valid email address must be provided to continue.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'Reset Password',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Passwords must be at least 8 characters in length.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Recovery Code',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'I Have My Device',
    ],

    'two_factor' => [
        'label' => 'Token logowania 2-etapowego',
        'label_help' => 'To konto wymaga uwierzytelniania 2-etapowego, aby kontynuować. Wprowadź wygenerowany kod, aby dokończyć logowanie.',
        'checkpoint_failed' => 'Kod uwierzytelniania 2-etapowego jest nieprawidłowy.',
    ],

    'throttle' => 'Zbyt wiele prób logowania. Spróbuj ponownie za :seconds sekund.',
    'password_requirements' => 'Hasło musi mieć co najmniej 8 znaków.',
    '2fa_must_be_enabled' => 'Administrator zażądał włączenia uwierzytelniania dwuetapowego dla Twojego konta, by móc korzystać z Panelu.',
];
