<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => 'Nebyl nalezen žádný účet odpovídající těmto přihlašovacím údajům.',

    'login' => [
        'title' => 'Login to Continue',
        'button' => 'Log In',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'Zapomněli jste heslo?',
        'label_help' => 'Zadejte e-mailovou adresu vašeho účtu pro příjem pokynů k obnovení hesla.',
        'button' => 'Send Email',
        'required' => [
            'email' => 'A valid email address must be provided to continue.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'Reset Password',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Passwords must be at least 8 characters in length.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Recovery Code',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'I Have My Device',
    ],

    'two_factor' => [
        'label' => 'Dvoufázový token',
        'label_help' => 'Tento účet vyžaduje druhou vrstvu ověřování, abyste mohli pokračovat. Pro dokončení přihlášení zadejte kód generovaný zařízením.',
        'checkpoint_failed' => 'Dvoufaktorový ověřovací token je neplatný.',
    ],

    'throttle' => 'Příliš mnoho pokusů o přihlášení. Zkuste to prosím znovu za :seconds sekund.',
    'password_requirements' => 'Heslo musí mít délku nejméně 8 znaků a mělo by být pro tento web jedinečné.',
    '2fa_must_be_enabled' => 'Správce požaduje, aby bylo dvoufázové ověření povoleno pro váš účet, aby jste mohl použit panel.',
];
