<?php

return [
    'title' => 'Account Overzicht',
    'email' => [
        'title' => 'Update Emailadres',
        'button' => 'Update Email',
        'updated' => 'Jouw primaire email is geupdatet.',
    ],
    'password' => [
        'title' => 'Update Wachtwoord',
        'button' => 'Update Wachtwoord',
        'requirements' => 'Jouw nieuwe wachtwoord zou te minste 8 karakters lang en uniek aan deze website moeten zijn.',
        'validation' => [
            'account_password' => 'Je moet jouw account wachtwoord opgeven.',
            'current_password' => 'Je moet jouw huidige wachtwoord opgeven.',
            'password_confirmation' => 'Wachtwoord bevesting komt niet overeen met het wachtwoord die je hebt ingevoerd.',
        ],
        'updated' => 'Jouw wachtwoord is geupdatet.',
    ],
    'two_factor' => [
        'title' => 'Twee-Staps Verificatie',
        'button' => 'Configureer twee-factor authenticatie',
        'disabled' => 'Two-factor authentication has been disabled on your account. You will no longer be prompted to provide a token when logging in.',
        'enabled' => 'Two-factor authentication has been enabled on your account! From now on, when logging in, you will be required to provide the code generated by your device.',
        'invalid' => 'The token provided was invalid.',
        'enable' => [
            'help' => 'Je hebt op dit moment geen tweestapsverificatie ingeschakeld voor jouw account. Klik op de onderstaande knop om te beginnen met het configureren ervan.',
            'button' => 'Schakel Twee-Staps in',
        ],
        'disable' => [
            'help' => 'Twee-staps verificatie is op dit moment ingeschakeld voor jouw account.',
            'title' => 'Schakel twee-factor authenticatie uit',
            'field' => 'Voer token in',
            'button' => 'Schakel Twee-Staps uit',
        ],
        'setup' => [
            'title' => 'Schakel Twee-Staps Verificatie in',
            'subtitle' => "Help protect your account from unauthorized access. You'll be prompted for a verification code each time you sign in.",
            'help' => 'Scan de bovenstaande QR-code met de tweestapsauthenticatie-app van uw keuze. Voer vervolgens de gegenereerde zescijferige code in het onderstaande veld in.',
        ],

        'required' => [
            'title' => '2-Factor Required',
            'description' => 'Your account must have two-factor authentication enabled in order to continue.',
        ],
    ],
];
