<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => 'ไม่พบบัญชีที่มีข้อมูลดังกล่าว',

    'login' => [
        'title' => 'Login to Continue',
        'button' => 'Log In',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'ลืมรหัสผ่านใช่หรือไม่',
        'label_help' => 'โปรดใส่อีเมลของคุณเพื่อรับวิธีการตั้งรหัสผ่านใหม่',
        'button' => 'กู้คืนบัญชี',
        'required' => [
            'email' => 'A valid email address must be provided to continue.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'รีเซ็ตรหัสผ่านและเข้าสู่ระบบ',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Passwords must be at least 8 characters in length.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Recovery Code',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'I Have My Device',
    ],

    'two_factor' => [
        'label' => 'โทเคน 2FA',
        'label_help' => 'บัญชีนี้ต้องมีการยืนยันตัวตนขั้นที่ 2 โปรดใส่รหัสจากอุปกรณ์ของท่านเพื่อเข้าสู่ระบบ',
        'checkpoint_failed' => 'โทเคนการยืนยันตัวตนแบบ 2 ขั้นตอนไม่ถูกต้อง',
    ],

    'throttle' => 'คุณได้พยายามเข้าระบบหลายครั้งเกินไป กรุณาลองใหม่ใน :seconds วินาที',
    'password_requirements' => 'รหัสผ่านต้องมีความยาวอย่างน้อย 8 ตัวอักษรและไม่ควรซ้ำกับเว็บไซต์อื่น',
    '2fa_must_be_enabled' => 'ผู้ดูแลระบบกำหนดให้บัญชีของท่านต้องมีการยืนยันตัวตนแบบ 2 ขั้นตอนจึงจะสามารถใช้งานได้',
];
