<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => 'Ingen konto fundet med de angivne oplysninger.',

    'login' => [
        'title' => 'Login to Continue',
        'button' => 'Log In',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'Glemt adgangskode?',
        'label_help' => 'Indtast din kontos e-mailadresse for at modtage instruktioner om nulstilling af din adgangskode.',
        'button' => 'Send Email',
        'required' => [
            'email' => 'A valid email address must be provided to continue.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'Reset Password',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Passwords must be at least 8 characters in length.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Recovery Code',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'I Have My Device',
    ],

    'two_factor' => [
        'label' => '2-Faktor Token',
        'label_help' => 'Denne konto kræver en anden form for godkendelse for at fortsætte. Indtast venligst koden genereret af din enhed for at fuldføre dette login.',
        'checkpoint_failed' => '2-faktor godkendelses-token var ugyldig.',
    ],

    'throttle' => 'For mange login forsøg. Prøv igen om :sekunder sekunder.',
    'password_requirements' => 'Adgangskoden skal være mindst 8 tegn lang og bør være unik for dette website.',
    '2fa_must_be_enabled' => 'Administratoren har krævet, at 2-faktor godkendelse skal være aktiveret for din konto for at bruge panelet.',
];
