<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => 'Účet s týmito údajmi nebol nájdený.',

    'login' => [
        'title' => 'Login to Continue',
        'button' => 'Log In',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'Zabudnuté heslo?',
        'label_help' => 'Zadajte emailovú adresu svojho účtu, aby ste dostali pokyny na reset hesla.',
        'button' => 'Send Email',
        'required' => [
            'email' => 'A valid email address must be provided to continue.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'Reset Password',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Passwords must be at least 8 characters in length.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Recovery Code',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'I Have My Device',
    ],

    'two_factor' => [
        'label' => 'Dvoj-faktorový kód',
        'label_help' => 'Tento účet vyžaduje dvoj-faktorové overenie. Prosím zadajte kód vygenerovaný Vašim zariadením.',
        'checkpoint_failed' => 'Dvoj-faktorový kód bol nesprávny.',
    ],

    'throttle' => 'Príliš veľa pokusov o prihlásnie. Prosím skúste to znovu o :seconds sekund.',
    'password_requirements' => 'Heslo musí mať aspoň 8 znakov a malo by byť výnimočné pre túto stránku.',
    '2fa_must_be_enabled' => 'Administrátor vyžaduje, aby bolo 2-faktorové overenie pre Váš účet zapnuté, aby ste mohli panel používať.',
];
