<?php

return [
    'email' => [
        'title' => 'Mettre à jour votre adresse e-mail',
        'updated' => 'Votre adresse e-mail a été mise à jour.',
    ],
    'password' => [
        'title' => 'Modifier votre mot de passe',
        'requirements' => 'Votre nouveau mot de passe doit comporter au moins 8 caractères.',
        'updated' => 'Votre mot de passe a été mis à jour.',
    ],
    'two_factor' => [
        'button' => 'Configure 2-Factor Authentication',
        'disabled' => 'Two-factor authentication has been disabled on your account. You will no longer be prompted to provide a token when logging in.',
        'enabled' => 'Two-factor authentication has been enabled on your account! From now on, when logging in, you will be required to provide the code generated by your device.',
        'invalid' => 'The token provided was invalid.',
        'setup' => [
            'title' => 'Setup two-factor authentication',
            'help' => 'Can\'t scan the code? Enter the code below into your application:',
            'field' => 'Saisir un jeton',
        ],
        'disable' => [
            'title' => 'Disable two-factor authentication',
            'field' => 'Saisir un jeton',
        ],
    ],
];
