<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => 'Er werd geen account gevonden dat overeenkomt met deze inloggegevens.',

    'login' => [
        'title' => 'Login to Continue',
        'button' => 'Log In',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'Wachtwoord Vergeten?',
        'label_help' => 'Voer het e-mailadres van uw account in om instructies te ontvangen over het opnieuw instellen van uw wachtwoord.',
        'button' => 'Send Email',
        'required' => [
            'email' => 'A valid email address must be provided to continue.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'Reset Password',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Passwords must be at least 8 characters in length.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Recovery Code',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'I Have My Device',
    ],

    'two_factor' => [
        'label' => 'Tweestapsverificatie code',
        'label_help' => 'Dit account heeft tweestapsverificatie aanstaan. Voer de door uw apparaat gegenereerde code in om deze login te voltooien.',
        'checkpoint_failed' => 'De tweestapsverificatie code was ongeldig.',
    ],

    'throttle' => 'Te veel inlogpogingen. Probeer het over :seconds seconden opnieuw.',
    'password_requirements' => 'Het wachtwoord moet minimaal 8 tekens lang zijn en moet uniek zijn voor deze site.',
    '2fa_must_be_enabled' => 'De beheerder heeft vereist dat tweestapsverificatie voor je account is ingeschakeld om het paneel te kunnen gebruiken.',
];
