apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: searcade-pelican-panel
  name: searcade-pelican-panel
spec:
  #  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: searcade-pelican-panel
  template:
    metadata:
      labels:
        app: searcade-pelican-panel
    spec:
      automountServiceAccountToken: false
      containers:
        - image: ghcr.io/stantabcorp/searcade-pelican-panel
          name: searcade-pelican-panel
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            periodSeconds: 30
            httpGet:
              port: 8000
              path: /up
              httpHeaders:
                - name: Host
                  value: panel-k8s.searcade.com
          envFrom:
            - configMapRef:
                name: searcade-pelican-panel-config
            - secretRef:
                name: searcade-pelican-panel-secret
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: searcade-pelican-panel-schedule
  name: searcade-pelican-panel-schedule
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 30
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          containers:
            - image: ghcr.io/stantabcorp/searcade-pelican-panel
              command:
                - /var/www/html/schedule.sh
              name: searcade-pelican-panel-schedule
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: searcade-pelican-panel-config
                - secretRef:
                    name: searcade-pelican-panel-secret
          restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: searcade-pelican-panel-queue
  name: searcade-pelican-panel-queue
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: searcade-pelican-panel-queue
  template:
    metadata:
      labels:
        app: searcade-pelican-panel-queue
    spec:
      automountServiceAccountToken: false
      containers:
        - image: ghcr.io/stantabcorp/searcade-pelican-panel
          name: searcade-pelican-panel
          command:
            - /var/www/html/queue.sh
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: searcade-pelican-panel-config
            - secretRef:
                name: searcade-pelican-panel-secret
