apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - deployment.yml
  - ingress.yml
  - service.yml
  - config.yml
namespace: searcade-pelican-panel
images:
  - name: ghcr.io/stantabcorp/searcade-pelican-panel
    newTag: main
