apiVersion: v1
kind: Service
metadata:
  labels:
    app: searcade-pelican-panel
  name: searcade-pelican-panel-svc
spec:
  ports:
    - port: 8000
      name: http
      protocol: TCP
      targetPort: 8000
  selector:
    app: searcade-pelican-panel
