<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => 'Non è stato trovato alcun account corrispondente a queste credenziali.',

    'login' => [
        'title' => 'Login to Continue',
        'button' => 'Log In',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'Password Dimenticata?',
        'label_help' => 'Inserisci l\'indirizzo email del tuo account per ricevere le istruzioni per reimpostare la password.',
        'button' => 'Send Email',
        'required' => [
            'email' => 'A valid email address must be provided to continue.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'Reset Password',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Passwords must be at least 8 characters in length.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Recovery Code',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'I Have My Device',
    ],

    'two_factor' => [
        'label' => 'Token a due fattori',
        'label_help' => 'Questo account richiede un secondo livello di autenticazione per continuare. Inserisci il codice generato dal tuo dispositivo per completare il login.',
        'checkpoint_failed' => 'Il token di autenticazione a due fattori non è valido.',
    ],

    'throttle' => 'Troppi tentativi di accesso. Riprova tra :seconds secondi.',
    'password_requirements' => 'La password deve essere di almeno 8 caratteri e deve essere unica per questo sito.',
    '2fa_must_be_enabled' => 'L\'amministratore ha richiesto che l\'autenticazione a due fattori sia abilitata per il tuo account per poter utilizzare il pannello.',
];
