<?php

return [
    'title' => 'Account Overview',
    'email' => [
        'title' => 'Update your email',
        'button' => 'Update Email',
        'updated' => 'Your email address has been updated.',
    ],
    'password' => [
        'title' => 'Change your password',
        'button' => 'Update Password',
        'requirements' => 'Your new password should be at least 8 characters in length.',
        'validation' => [
            'account_password' => 'You must provide your account password.',
            'current_password' => 'You must provide your current password.',
            'password_confirmation' => 'Password confirmation does not match the password you entered.',
        ],
        'updated' => 'Your password has been updated.',
    ],
    'two_factor' => [
        'title' => 'Two-Step Verification',
        'button' => 'Configure 2-Factor Authentication',
        'disabled' => 'Two-factor authentication has been disabled on your account. You will no longer be prompted to provide a token when logging in.',
        'enabled' => 'Two-factor authentication has been enabled on your account! From now on, when logging in, you will be required to provide the code generated by your device.',
        'invalid' => 'The token provided was invalid.',
        'enable' => [
            'help' => 'You do not currently have two-step verification enabled on your account. Click the button below to begin configuring it.',
            'button' => 'Enable Two-Step',
        ],
        'disable' => [
            'help' => 'Two-step verification is currently enabled on your account.',
            'title' => 'Disable two-factor authentication',
            'field' => 'Enter token',
            'button' => 'Disable Two-Step',
        ],
        'setup' => [
            'title' => 'Setup two-factor authentication',
            'subtitle' => "Help protect your account from unauthorized access. You'll be prompted for a verification code each time you sign in.",
            'help' => 'Can\'t scan the code? Enter the code below into your application:',
        ],

        'required' => [
            'title' => '2-Factor Required',
            'description' => 'Your account must have two-factor authentication enabled in order to continue.',
        ],
    ],
];
