<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => 'Käyttäjätunnuksia vastaavaa tiliä ei löytynyt.',

    'login' => [
        'title' => 'Login to Continue',
        'button' => 'Log In',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'Unohtuiko salasana?',
        'label_help' => 'Syötä tilisi sähköpostiosoite saadaksesi ohjeet salasanan vaihtamista varten.',
        'button' => 'Send Email',
        'required' => [
            'email' => 'A valid email address must be provided to continue.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'Reset Password',
        'new_password' => 'Uusi Salasana',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Passwords must be at least 8 characters in length.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Recovery Code',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'Minulla On Laitteeni',
    ],

    'two_factor' => [
        'label' => 'Kaksivaiheinen Tunnus',
        'label_help' => 'Tämä tunnus vaatii kaksivaiheisen todennuksen jatkaaksesi. Ole hyvä ja syötä laitteesi luoma koodi, jotta voit suorittaa tämän kirjautumisen.',
        'checkpoint_failed' => 'Kaksivaiheisen todennuksen avain oli virheellinen.',
    ],

    'throttle' => 'Liian monta kirjautumisyritystä. Yritä uudelleen :seconds sekunnin kuluttua.',
    'password_requirements' => 'Salasanan on oltava vähintään 8 merkkiä pitkä ja sen tulisi olla ainutkertainen tälle sivustolle.',
    '2fa_must_be_enabled' => 'Järjestelmänvalvoja on vaatinut, että kaksivaiheinen todennus on oltava käytössä tililläsi, jotta voit käyttää paneelia.',
];
