<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => 'لم يتم العثور على حساب يتطابق مع هذه البيانات.',

    'login' => [
        'title' => 'Login to Continue',
        'button' => 'Log In',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'نسيت كلمة المرور؟',
        'label_help' => 'أدخل عنوان بريدك الإلكتروني لتتلقى تعليمات حول إعادة تعيين كلمة المرور.',
        'button' => 'Send Email',
        'required' => [
            'email' => 'A valid email address must be provided to continue.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'Reset Password',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Passwords must be at least 8 characters in length.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Recovery Code',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'I Have My Device',
    ],

    'two_factor' => [
        'label' => 'رمز التحقق ذو العاملين',
        'label_help' => 'هذا الحساب يتطلب طبقة ثانية من التحقق للمتابعة. الرجاء إدخال الرمز المولد على جهازك لإكمال هذا التسجيل.',
        'checkpoint_failed' => 'رمز التحقق ذو العاملين كان غير صالح.',
    ],

    'throttle' => 'عدد محاولات تسجيل الدخول كثيرة جداً. يرجى المحاولة مجدداً بعد :seconds ثوانٍ.',
    'password_requirements' => 'يجب أن تكون كلمة المرور بطول 8 أحرف على الأقل وأن تكون فريدة لهذا الموقع.',
    '2fa_must_be_enabled' => 'يتطلب المدير تفعيل التحقق ذو العاملين لحسابك لاستخدام اللوحة.',
];
