<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => 'No account matching those credentials could be found.',

    'login' => [
        'title' => 'Login to Continue',
        'button' => 'Log In',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'Forgot Password?',
        'label_help' => 'Enter your account email address to receive instructions on resetting your password.',
        'button' => 'Recover Account',
        'required' => [
            'email' => 'A valid email address must be provided to continue.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'Reset and Sign In',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Passwords must be at least 8 characters in length.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Recovery Code',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'Aš turiu savo įrenginį',
    ],

    'two_factor' => [
        'label' => 'Dviejų faktorių kodas',
        'label_help' => 'Ši paskyra reikalauja antro lygio autentifikacijos, kad tęsti. Prašau įvesti kodą generuotą jūsų įrenginio, kad užbaigti prisijungimą.',
        'checkpoint_failed' => 'Dviejų faktorių autentifikacijos kodas buvo negaliojantis.',
    ],

    'throttle' => 'Per daug prisijungimo bandymų. Prašome pabandyti dar kartą po :seconds sekundžių.',
    'password_requirements' => 'Slaptažodis turi būti bent jau 8 simbolių ilgio ir turi būti išskirtinis šiai svetainei.',
    '2fa_must_be_enabled' => 'Administratorius reikalauja, kad dviejų faktorių autentifikacija būtų įjungta jūsų paskyrai, kad jūs galėtūmėte naudotis šiuo Panel.',
];
