<?php

return [
    'email' => [
        'title' => 'Oppdater e-postadressen din',
        'updated' => 'Din epost har blitt oppdatert',
    ],
    'password' => [
        'title' => 'Endre passoret ditt',
        'requirements' => 'Ditt nye passord må ha minst 8 tegn',
        'updated' => 'Ditt passord er oppdatert.',
    ],
    'two_factor' => [
        'button' => 'Konfigurer tofaktorautentisering',
        'disabled' => 'Two-factor authentication has been disabled on your account. You will no longer be prompted to provide a token when logging in.',
        'enabled' => 'Two-factor authentication has been enabled on your account! From now on, when logging in, you will be required to provide the code generated by your device.',
        'invalid' => 'Koden som ble oppgitt var ugyldig',
        'setup' => [
            'title' => 'Sett opp tofaktorautentisering',
            'help' => 'Can\'t scan the code? Enter the code below into your application:',
            'field' => 'Skriv inn autentiserings-kode',
        ],
        'disable' => [
            'title' => 'Deaktiver tofaktorautentisering',
            'field' => 'Skriv inn autentiserings-kode',
        ],
    ],
];
