<?php

return [
    'title' => 'Account Overview',
    'email' => [
        'title' => 'Oppdater e-postadressen din',
        'button' => 'Update Email',
        'updated' => 'Din epost har blitt oppdatert',
    ],
    'password' => [
        'title' => 'Endre passoret ditt',
        'button' => 'Update Password',
        'requirements' => 'Ditt nye passord må ha minst 8 tegn',
        'validation' => [
            'account_password' => 'You must provide your account password.',
            'current_password' => 'You must provide your current password.',
            'password_confirmation' => 'Password confirmation does not match the password you entered.',
        ],
        'updated' => 'Ditt passord er oppdatert.',
    ],
    'two_factor' => [
        'title' => 'Two-Step Verification',
        'button' => 'Konfigurer tofaktorautentisering',
        'disabled' => 'Two-factor authentication has been disabled on your account. You will no longer be prompted to provide a token when logging in.',
        'enabled' => 'Two-factor authentication has been enabled on your account! From now on, when logging in, you will be required to provide the code generated by your device.',
        'invalid' => 'Koden som ble oppgitt var ugyldig',
        'enable' => [
            'help' => 'You do not currently have two-step verification enabled on your account. Click the button below to begin configuring it.',
            'button' => 'Enable Two-Step',
        ],
        'disable' => [
            'help' => 'Two-step verification is currently enabled on your account.',
            'title' => 'Deaktiver tofaktorautentisering',
            'field' => 'Skriv inn autentiserings-kode',
            'button' => 'Disable Two-Step',
        ],
        'setup' => [
            'title' => 'Sett opp tofaktorautentisering',
            'subtitle' => "Help protect your account from unauthorized access. You'll be prompted for a verification code each time you sign in.",
            'help' => 'Can\'t scan the code? Enter the code below into your application:',
        ],

        'required' => [
            'title' => '2-Factor Required',
            'description' => 'Your account must have two-factor authentication enabled in order to continue.',
        ],
    ],
];
