<?php

return [
    'return_to_login' => 'Return to Login',
    'failed' => 'Bu kimlik bilgileriyle eşleşen hesap bulunamadı.',

    'login' => [
        'title' => 'Login to Continue',
        'button' => 'Log In',
        'required' => [
            'username_or_email' => 'A username or email must be provided.',
            'password' => 'Please enter your account password.',
        ],
    ],

    'forgot_password' => [
        'title' => 'Request Password Reset',
        'label' => 'Şifremi Unuttum',
        'label_help' => 'Şifrenizi sıfırlama talimatlarını almak için e-posta adresinizi giriniz.',
        'button' => 'Send Email',
        'required' => [
            'email' => 'A valid email address must be provided to continue.',
        ],
    ],

    'reset_password' => [
        'title' => 'Reset Password',
        'button' => 'Reset Password',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'requirement' => [
            'password' => 'Passwords must be at least 8 characters in length.',
        ],
        'required' => [
            'password' => 'A new password is required.',
            'password_confirmation' => 'Your new password does not match.',
        ],
        'validation' => [
            'password' => 'Your new password should be at least 8 characters in length.',
            'password_confirmation' => 'Your new password does not match.',
        ],
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery_code' => 'Recovery Code',
        'recovery_code_description' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'authentication_code' => 'Authentication Code',
        'authentication_code_description' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost_device' => "I've Lost My Device",
        'have_device' => 'I Have My Device',
    ],

    'two_factor' => [
        'label' => 'İki Faktörlü Doğrulama Tokeni',
        'label_help' => 'Bu hesabın devam edebilmesi için ikinci bir kimlik doğrulama katmanı gerekiyor. Bu girişi tamamlamak için lütfen cihazınız tarafından oluşturulan kodu girin.',
        'checkpoint_failed' => 'İki faktörlü kimlik doğrulama jetonu geçersiz.',
    ],

    'throttle' => 'Çok fazla hatalı giriş yaptınız. Lütfen :seconds saniye sonra tekrar deneyiniz.',
    'password_requirements' => 'Şifre en az 8 karakter uzunluğunda olmalı.',
    '2fa_must_be_enabled' => 'Yönetici, Paneli kullanabilmeniz için hesabınızda 2 Faktörlü Kimlik Doğrulamanın etkinleştirilmesini zorunlu kılmıştır.',
];
